---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dex
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dex
rules:
  - apiGroups: ["dex.coreos.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: dex
  namespace: {{ .Release.Namespace }}
#
#apiVersion: rbac.authorization.k8s.io/v1alpha1
#kind: ClusterRole
#metadata:
#  name: dex
#rules:
#- apiGroups: ["dex.coreos.com"] # API group created by dex
#  resources: ["*"]
#  verbs: ["*"]
#- apiGroups: ["apiextensions.k8s.io"]
#  resources: ["customresourcedefinitions"]
#  verbs: ["create"] # To manage its own resources identity must be able to create customresourcedefinitions.
#---
#apiVersion: rbac.authorization.k8s.io/v1alpha1
#kind: ClusterRoleBinding
#metadata:
#  name: dex
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: admin
##  name: dex
#subjects:
#- kind: ServiceAccount
#  name: dex                 # Service account assigned to the dex pod.
#  namespace: {{ .Release.Namespace }}  # The namespace dex is running in.
#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: dex
#  namespace: {{ .Release.Namespace }}
