# TLS
{{- if .Values.tls }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}.tls
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
data:
  tls.ca: {{ .Values.tls.ca }}
  tls.crt: {{ .Values.tls.cert }}
  tls.key: {{ .Values.tls.key }}
{{- end }}

# Github Secret
{{- if .Values.connector.GitHub }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}.github
type: Opaque
data:
  client-id: {{ .Values.connector.GitHub.ClientId }}
  client-secret: {{ .Values.connector.GitHub.ClientSecret }}
{{- end }}

# OIDC
{{- if .Values.connector.Oidc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}.oidc
type: Opaque
data:
  client-id: {{ .Values.connector.Oidc.ClientId }}
  client-secret: {{ .Values.connector.Oidc.ClientSecret }}
{{- end }}
